<?php

declare(strict_types = 1);

namespace Phuxtil\Flysystem\SshShell;

/**
 * Code generated by POPO generator, do not edit.
 */
class SshShellConfigurator 
{
    /**
     * @var array
     */
    protected $data = array (
  'user' => '',
  'host' => '',
  'privateKey' => '',
  'authType' => 'config',
  'root' => '/tmp',
  'port' => 22,
);

    /**
     * @var array
     */
    protected $default = array (
  'user' => '',
  'host' => '',
  'privateKey' => '',
  'authType' => 'config',
  'root' => '/tmp',
  'port' => 22,
);

    /**
    * @var array
    */
    protected $propertyMapping = array (
  'user' => 'string',
  'host' => 'string',
  'privateKey' => 'string',
  'authType' => 'string',
  'root' => 'string',
  'port' => 'int',
);

    /**
    * @var array
    */
    protected $collectionItems = array (
  'user' => '',
  'host' => '',
  'privateKey' => '',
  'authType' => '',
  'root' => '',
  'port' => '',
);

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            return null;
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    /**
     * @return array
     */
    public function toArray(): array
    {
        $data = [];
        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = $this->default[$key] ?? null;

            if (isset($this->data[$key])) {
                $value = $this->data[$key];

                if ($this->collectionItems[$key] !== '') {
                    if (\is_array($value) && \class_exists($this->collectionItems[$key])) {
                        foreach ($value as $popo) {
                            if (\method_exists($popo, 'toArray')) {
                                $data[$key][] = $popo->toArray();
                            }
                        }
                    }
                } else {
                    $data[$key] = $value;
                }

                if (\is_object($value) && \method_exists($value, 'toArray')) {
                    $data[$key] = $value->toArray();
                }
            }
        }

        return $data;
    }

    public function fromArray(array $data): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $result = [];
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key, $data)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (\method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                } else {
                    $result[$key] = $data[$key];
                }
            }

            if (\is_array($result[$key]) && \class_exists($type)) {
                $popo = new $type();
                if (\method_exists($popo, 'fromArray')) {
                    $popo->fromArray($result[$key]);
                }
                $result[$key] = $popo;
            }
        }

        $this->data = $result;

        return $this;
    }

    protected function isCollectionItem(string $key, array $data): bool
    {
        return $this->collectionItems[$key] !== '' &&
            \is_array($data[$key]) &&
            \class_exists($this->collectionItems[$key]);
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @throws \InvalidArgumentException
     * @return void
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = \trim(\strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!\is_array($collection) || $type !== 'array') {
            throw new \InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    
    /**
     * @return string|null
     */
    public function getUser(): ?string
    {
        return $this->popoGetValue('user');
    }

    /**
     * @param string|null $user
     *
     * @return self
     */
    public function setUser(?string $user): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('user', $user);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireUser(): string
    {
        $this->assertPropertyValue('user');

        return (string)$this->popoGetValue('user');
    }

    /**
     * @return string|null
     */
    public function getHost(): ?string
    {
        return $this->popoGetValue('host');
    }

    /**
     * @param string|null $host
     *
     * @return self
     */
    public function setHost(?string $host): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('host', $host);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireHost(): string
    {
        $this->assertPropertyValue('host');

        return (string)$this->popoGetValue('host');
    }

    /**
     * @return string|null
     */
    public function getPrivateKey(): ?string
    {
        return $this->popoGetValue('privateKey');
    }

    /**
     * @param string|null $privateKey
     *
     * @return self
     */
    public function setPrivateKey(?string $privateKey): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('privateKey', $privateKey);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requirePrivateKey(): string
    {
        $this->assertPropertyValue('privateKey');

        return (string)$this->popoGetValue('privateKey');
    }

    /**
     * @return string|null
     */
    public function getAuthType(): ?string
    {
        return $this->popoGetValue('authType');
    }

    /**
     * @param string|null $authType
     *
     * @return self
     */
    public function setAuthType(?string $authType): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('authType', $authType);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireAuthType(): string
    {
        $this->assertPropertyValue('authType');

        return (string)$this->popoGetValue('authType');
    }

    /**
     * @return string|null
     */
    public function getRoot(): ?string
    {
        return $this->popoGetValue('root');
    }

    /**
     * @param string|null $root
     *
     * @return self
     */
    public function setRoot(?string $root): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('root', $root);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireRoot(): string
    {
        $this->assertPropertyValue('root');

        return (string)$this->popoGetValue('root');
    }

    /**
     * @return integer|null
     */
    public function getPort(): ?int
    {
        return $this->popoGetValue('port');
    }

    /**
     * @param integer|null $port
     *
     * @return self
     */
    public function setPort(?int $port): \Phuxtil\Flysystem\SshShell\SshShellConfigurator
    {
        $this->popoSetValue('port', $port);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return integer
     */
    public function requirePort(): int
    {
        $this->assertPropertyValue('port');

        return (int)$this->popoGetValue('port');
    }


    
}
